# Generated by Django 5.2.17 on 2026-10-07 04:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='staff_count',
            field=models.PositiveIntegerField(default=1, help_text='How many customers can be served at the same time (staff or chairs)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
