# Generated by Django 5.2.17 on 2026-09-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], default='cash', max_length=10)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('services', models.ManyToManyField(related_name='bookings', to='salon.service')),
            ],
            options={
                'ordering': ['date', 'time'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('date', 'time'), name='unique_active_slot')],
            },
        ),
    ]
