# Generated by Django 5.2.17 on 2026-10-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_total_amount'),
        ('salon', '0002_salon_staff_count'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_active_slot',
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['date', 'time'], name='bookings_bo_date_9ed98b_idx'),
        ),
    ]
